/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as GeospatialRouteImport } from './routes/geospatial'
import { Route as CriminalsRouteImport } from './routes/criminals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const GeospatialRoute = GeospatialRouteImport.update({
  id: '/geospatial',
  path: '/geospatial',
  getParentRoute: () => rootRouteImport,
} as any)
const CriminalsRoute = CriminalsRouteImport.update({
  id: '/criminals',
  path: '/criminals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminals': typeof CriminalsRoute
  '/geospatial': typeof GeospatialRoute
  '/network': typeof NetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminals': typeof CriminalsRoute
  '/geospatial': typeof GeospatialRoute
  '/network': typeof NetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminals': typeof CriminalsRoute
  '/geospatial': typeof GeospatialRoute
  '/network': typeof NetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/criminals' | '/geospatial' | '/network'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/criminals' | '/geospatial' | '/network'
  id:
    '__root__' | '/' | '/analytics' | '/criminals' | '/geospatial' | '/network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CriminalsRoute: typeof CriminalsRoute
  GeospatialRoute: typeof GeospatialRoute
  NetworkRoute: typeof NetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geospatial': {
      id: '/geospatial'
      path: '/geospatial'
      fullPath: '/geospatial'
      preLoaderRoute: typeof GeospatialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criminals': {
      id: '/criminals'
      path: '/criminals'
      fullPath: '/criminals'
      preLoaderRoute: typeof CriminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CriminalsRoute: CriminalsRoute,
  GeospatialRoute: GeospatialRoute,
  NetworkRoute: NetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
